[tool]
id = "com.thelightphone.botany"
label = "Botany"
versionCode = 1
versionName = "0.1.0"
permissions = ["android.permission.INTERNET", "android.permission.CAMERA"]
serverPackage = "com.lightos"
#serverPackage = "com.thelightphone.sdk.emulator"
